## Ambil Api Key

In [59]:
import httpx
url = "http://10.12.1.35:8585/apikey"

payload = {
    "username": "MaxDelta",
    "otp": "561930"
}

try:
    with httpx.Client(timeout=10.0) as client:
        response = client.post(url, json=payload)
        response.raise_for_status()
        data = response.json()
        
    print("Response:", data)
    
    api_key = data.get("api_key")
    print("API Key:", api_key)

except httpx.HTTPStatusError as e:
    print("HTTP Error:", e.response.status_code, e.response.text)

except httpx.RequestError as e:
    print("Request Error:", str(e))

Response: {'api_key': 'pr-GLv7n8xrOztYJNz-xxhhSIYotbwqEyIMLPs0VKWEb4A'}
API Key: pr-GLv7n8xrOztYJNz-xxhhSIYotbwqEyIMLPs0VKWEb4A

## Ambil Dataset

In [ ]:
from datasets import load_dataset

test_dataset = load_dataset(
    "fahadh4ilyas/indonesian_news_datasets",
    split="test",
    token="hf_xxxxxxxxxxxxx" 
)

test_dataset

Dataset({
    features: ['id', 'source', 'title', 'image', 'url', 'content', 'date', 'embedding', 'created_at', 'updated_at', 'summary', 'nomic_embedding', 'label'],
    num_rows: 6459
})

In [61]:
import pandas as pd

test_df = pd.DataFrame(test_dataset)
test_df.head()

,id,source,title,image,url,content,date,embedding,created_at,updated_at,summary,nomic_embedding,label
0,3769,cnnindonesia,"Sidak di Kantor Pajak Solo, Jokowi Pamer Setor...",https://akcdn.detik.net.id/visual/2023/02/06/p...,https://www.cnnindonesia.com/nasional/20230309...,Presiden JokoWidodo( Jokowi )melakukan inspeks...,2023-03-09 10:23:49,"[-0.006528483,-0.016078303,0.019445695,-0.0227...",2023-03-09 11:05:15.323051,2023-03-09 11:05:15.323051,Presiden Jokowi bersama dengan Menteri Keuanga...,"[-0.27555179595947266, 0.7974510788917542, -2....",POLITIK_PEMERINTAHAN
1,36770,kumparan,5 Contoh Soal Advertisement Kelas 9 untuk Bela...,https://blue.kumparan.com/image/upload/fl_prog...,https://kumparan.com/berita-terkini/5-contoh-s...,Advertisement merupakan salah satu materi dala...,2023-03-27 12:15:11,"[0.006514681,0.011406955,0.005211745,-0.017439...",2023-03-27 12:20:12.787908,2023-03-27 12:20:12.787908,Materi advertisement mengenalkan siswa tentang...,"[0.14575253427028656, 1.7195326089859009, -2.4...",EKONOMI_BISNIS
2,32538,kumparan,Dimensi Sosial dalam Puasa Ramadhan,https://blue.kumparan.com/image/upload/fl_prog...,https://kumparan.com/faisal-dudayef15397841851...,Puasa Ramadhan adalah salah satu ibadah pentin...,2023-03-25 11:48:05,"[-0.009245157,-0.009270434,0.020424023,-0.0065...",2023-03-25 12:20:16.571114,2023-03-25 12:20:16.571114,Puasa Ramadhan diwajibkan bagi umat Muslim dan...,"[0.8499172329902649, 0.29111120104789734, -2.2...",POLITIK_PEMERINTAHAN
3,9979,kumparan,"Jalur Rel Terkena Longsor, Perjalanan Kereta P...",https://blue.kumparan.com/image/upload/fl_prog...,https://kumparan.com/kumparannews/jalur-rel-te...,Longsor terjadi di sekitar area jalur rek kere...,2023-03-15 00:56:19,"[0.007497486,-0.029989945,0.012072223,-7.43018...",2023-03-15 01:50:15.84186,2023-03-15 01:50:15.84186,Longsor terjadi di jalur Kereta Api Pangrango ...,"[0.6692487597465515, 0.9170069098472595, -2.81...",BENCANA_LINGKUNGAN
4,29714,tempo,"Ada Trojan Perbankan Versi Baru, Kaspersky Seb...",https://statik.tempo.co/data/2020/04/18/id_931...,https://bisnis.tempo.co/read/1706385/ada-troja...,"TEMPO.CO, Jakarta - Pakar dari Kaspersky telah...",2023-03-24 02:02:21,"[-0.020842083,-0.031541903,0.013520802,-0.0256...",2023-03-24 02:30:19.971467,2023-03-24 02:30:19.971467,"Emotet, program malware komputer yang awalnya ...","[0.22268828749656677, 1.3627448081970215, -2.8...",TEKNOLOGI_DIGITAL

## Engine Klasifikasi News

In [134]:
import httpx
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock

BASE_URL = "http://10.12.1.35:8585"
MODEL_NAME = "Qwen3-4B"
MAX_WORKERS = 10
SUMMARY_MAX_CHARS = 4000
OUTPUT_FILE = "hasil_klasifikasi_news.csv"

VALID_LABELS = {
    "POLITIK_PEMERINTAHAN",
    "EKONOMI_BISNIS",
    "HUKUM_KRIMINAL",
    "OLAHRAGA",
    "TEKNOLOGI_DIGITAL",
    "BENCANA_LINGKUNGAN"
}

SYSTEM_PROMPT = (
    "You are a strict Indonesian news classification system. "
    "Your only task is to read a news article and output exactly one of these 6 labels: "
    "POLITIK_PEMERINTAHAN, EKONOMI_BISNIS, HUKUM_KRIMINAL, OLAHRAGA, TEKNOLOGI_DIGITAL, BENCANA_LINGKUNGAN. "
    "Never output anything else. No explanations, no punctuation, no extra text. Just the label."
)

CLASSIFICATION_PROMPT = """Classify the following Indonesian news article into exactly ONE of these 6 labels:

POLITIK_PEMERINTAHAN
EKONOMI_BISNIS
HUKUM_KRIMINAL
OLAHRAGA
TEKNOLOGI_DIGITAL
BENCANA_LINGKUNGAN

CATEGORY DEFINITIONS:
- POLITIK_PEMERINTAHAN: news about how a country or region is governed and managed through political processes, including government decisions, policies, elections, diplomacy, and state institutions
- EKONOMI_BISNIS: news about the production, distribution, and consumption of goods and services, including financial markets, trade, investment, and business activities
- HUKUM_KRIMINAL: news about the system of rules, enforcement of laws, criminal acts, and the judicial process
- OLAHRAGA: news where the PRIMARY topic is an ongoing or completed sports competition, athlete performance result, or sporting event outcome — not a sports figure's non-sport activity, not sports business, not sports policy
- TEKNOLOGI_DIGITAL: news where the PRIMARY topic is a technology product, digital platform, or tech innovation — not merely mentioning a tool or app in passing
- BENCANA_LINGKUNGAN: news where the PRIMARY topic is a natural disaster (flood, earthquake, landslide, eruption, wildfire) or environmental damage actively occurring — NOT accidents, crimes, or human-caused incidents

DISAMBIGUATION RULES:

POLITIK vs EKONOMI:
- Ask: is the main actor a government/state institution making a political decision? → POLITIK_PEMERINTAHAN
- Ask: is the main actor a company, market, or private sector? → EKONOMI_BISNIS
- Government issues policy or regulation → POLITIK_PEMERINTAHAN
- State budget (APBN/APBD) approval or debate → POLITIK_PEMERINTAHAN
- Company earnings, stock market, private investment, business merger → EKONOMI_BISNIS
- Trade data, inflation, GDP, economic indicators (reported, not decided) → EKONOMI_BISNIS
- Government economic program where the policy decision is the focus → POLITIK_PEMERINTAHAN
- Government economic program where the economic impact/data is the focus → EKONOMI_BISNIS
- News about prices, commodities, supply chain, exports, imports → EKONOMI_BISNIS even if government is mentioned
- News about banks, insurance, fintech, capital markets → EKONOMI_BISNIS even if regulated by government
- News about UMKM, entrepreneurs, cooperatives, industry sectors → EKONOMI_BISNIS

HUKUM_KRIMINAL takes priority over BENCANA_LINGKUNGAN:
- Victims or casualties caused by human action (crime, negligence, accident, violence) → HUKUM_KRIMINAL
- Fire caused by humans or unknown cause → HUKUM_KRIMINAL (not BENCANA)
- Building collapse due to construction fault → HUKUM_KRIMINAL (not BENCANA)
- Traffic accident with casualties → HUKUM_KRIMINAL (not BENCANA)
- Corruption, bribery, fraud, money laundering, KPK, police arrest, court verdict → HUKUM_KRIMINAL (never POLITIK)
- Government official arrested or on trial → HUKUM_KRIMINAL (not POLITIK, even if they are a politician)

BENCANA_LINGKUNGAN only when:
- The natural disaster itself (flood, earthquake, landslide, volcanic eruption, tsunami, wildfire from nature) is the PRIMARY topic
- Includes: scale of damage, number of displaced people, rescue operations in progress
- BMKG weather warning where the weather event is the main focus
- Government response or policy about a disaster → POLITIK_PEMERINTAHAN (not BENCANA)
- Disaster relief budget → EKONOMI_BISNIS (not BENCANA)

OLAHRAGA only when:
- The match, competition, tournament, or athlete performance IS the main topic
- Includes: match results, standings, player transfers, training camp, injury news
- Does NOT include: sports corruption → HUKUM_KRIMINAL, sports funding policy → POLITIK_PEMERINTAHAN

TEKNOLOGI_DIGITAL:
- Tech mentioned only as context → use the more appropriate label instead
- Tech regulation by government → TEKNOLOGI_DIGITAL (not POLITIK)

OUT-OF-SCOPE MAPPING:
- Entertainment, film, music, celebrity → EKONOMI_BISNIS
- Religion, culture, tourism as industry → EKONOMI_BISNIS
- Lifestyle, food, travel (non-policy) → EKONOMI_BISNIS
- Trivia, crossword, quiz, games → TEKNOLOGI_DIGITAL
- Science, research, innovation → TEKNOLOGI_DIGITAL
- Education policy, school regulation, national curriculum → POLITIK_PEMERINTAHAN
- Social welfare policy, poverty alleviation program → POLITIK_PEMERINTAHAN
- Public health policy, hospital regulation, national health program → POLITIK_PEMERINTAHAN

CRITICAL RULES:
- You MUST output ONLY one of the 6 labels above, nothing else.
- Do NOT output any label outside the 6 above under any circumstance.
- Do NOT write explanations, reasoning, or punctuation.
- Even if the article is completely unrelated, you MUST still choose the closest one from the 6 labels.

Title: {title}
Content: {content}

Label:"""


def normalize_label(raw: str) -> str | None:
    cleaned = raw.strip().upper().replace(" ", "_").replace("-", "_")
    if cleaned in VALID_LABELS:
        return cleaned
    for label in VALID_LABELS:
        if cleaned in label or label.split("_")[0] == cleaned:
            return label
    return None


def classify_news(title: str, content: str, api_key: str) -> tuple[str | None, str | None]:
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": CLASSIFICATION_PROMPT.format(title=title, content=content)}
        ],
        "temperature": 0.1,
        "top_p": 0.9,
        "max_tokens": 20,
        "chat_template_kwargs": {"enable_thinking": False}
    }

    with httpx.Client(timeout=60.0) as client:
        response = client.post(f"{BASE_URL}/v1/chat/completions", json=payload, headers=headers)
        response.raise_for_status()
        data = response.json()

    raw_label = data["choices"][0]["message"]["content"].strip()
    return normalize_label(raw_label), data.get("id")


def process_row(row: dict, api_key: str) -> dict:
    try:
        predicted_label, response_id = classify_news(
            title=row["title"],
            content=row["content"][:SUMMARY_MAX_CHARS],
            api_key=api_key
        )
        return {**row, "predicted_label": predicted_label, "response_id": response_id, "error": None}
    except Exception as e:
        return {**row, "predicted_label": None, "response_id": None, "error": str(e)}


def run_batch(rows: list[dict], api_key: str) -> list[dict]:
    total = len(rows)
    results = [None] * total
    counter = {"done": 0}
    lock = Lock()

    print(f"Memproses {total} artikel dengan {MAX_WORKERS} workers...\n")

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_idx = {
            executor.submit(process_row, row, api_key): idx
            for idx, row in enumerate(rows)
        }
        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]
            result = future.result()
            results[idx] = result

            with lock:
                counter["done"] += 1
                done = counter["done"]

            status = f"[ERROR: {result['error']}]" if result["error"] else result["predicted_label"]
            print(f"({done}/{total}) ID: {result.get('id', '?')} → {status}")

    return results

In [135]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock

rows = list(test_dataset)
total = len(rows)
results = [None] * total
counter = {"done": 0}
lock = Lock()

def process_row(idx: int, row: dict):
    try:
        predicted_label, response_id = classify_news(
            title=row["title"],
            content=row["content"][:4000],
            api_key=api_key
        )
        results[idx] = {
            "id": row["id"],
            "label": row["label"],
            "predicted_label": predicted_label,
            "response_id": response_id,
            "error": None
        }
    except Exception as e:
        results[idx] = {
            "id": row["id"],
            "label": row["label"],
            "predicted_label": None,
            "response_id": None,
            "error": str(e)
        }
    finally:
        with lock:
            counter["done"] += 1
            done = counter["done"]
        status = results[idx]["predicted_label"] or f"ERROR: {results[idx]['error']}"
        print(f"({done}/{total}) ID: {row['id']} → {status}")

with ThreadPoolExecutor(max_workers=10) as executor:
    futures = [executor.submit(process_row, idx, row) for idx, row in enumerate(rows)]
    for future in as_completed(futures):
        future.result()

print(f"\nSelesai. Sukses: {sum(1 for r in results if r['predicted_label'])} | Error: {sum(1 for r in results if r['error'])}")

(1/6459) ID: 24660 → HUKUM_KRIMINAL
(2/6459) ID: 3769 → EKONOMI_BISNIS
(3/6459) ID: 32538 → POLITIK_PEMERINTAHAN
(4/6459) ID: 52720 → HUKUM_KRIMINAL
(5/6459) ID: 4765 → HUKUM_KRIMINAL
(6/6459) ID: 29714 → TEKNOLOGI_DIGITAL
(7/6459) ID: 9979 → BENCANA_LINGKUNGAN
(8/6459) ID: 36770 → EKONOMI_BISNIS
(9/6459) ID: 52849 → POLITIK_PEMERINTAHAN
(10/6459) ID: 16192 → BENCANA_LINGKUNGAN
(11/6459) ID: 58657 → OLAHRAGA
(12/6459) ID: 23291 → HUKUM_KRIMINAL
(13/6459) ID: 61426 → POLITIK_PEMERINTAHAN
(14/6459) ID: 37597 → EKONOMI_BISNIS
(15/6459) ID: 22833 → EKONOMI_BISNIS
(16/6459) ID: 50796 → POLITIK_PEMERINTAHAN
(17/6459) ID: 37999 → HUKUM_KRIMINAL
(18/6459) ID: 16546 → EKONOMI_BISNIS
(19/6459) ID: 61901 → EKONOMI_BISNIS
(20/6459) ID: 48278 → POLITIK_PEMERINTAHAN
(21/6459) ID: 26214 → POLITIK_PEMERINTAHAN
(22/6459) ID: 24987 → POLITIK_PEMERINTAHAN
(23/6459) ID: 56363 → HUKUM_KRIMINAL
(24/6459) ID: 19294 → POLITIK_PEMERINTAHAN
(25/6459) ID: 33039 → EKONOMI_BISNIS
(26/6459) ID: 9562 → HUKUM_KRIMINAL
(27/6459) ID: 21544 → EKONOMI_BISNIS
(28/6459) ID: 53150 → POLITIK_PEMERINTAHAN
(29/6459) ID: 13174 → BENCANA_LINGKUNGAN
(30/6459) ID: 30899 → EKONOMI_BISNIS
(31/6459) ID: 7636 → OLAHRAGA
(32/6459) ID: 16239 → OLAHRAGA
(33/6459) ID: 50544 → HUKUM_KRIMINAL
(34/6459) ID: 38398 → BENCANA_LINGKUNGAN
(35/6459) ID: 26041 → BENCANA_LINGKUNGAN
(36/6459) ID: 57200 → POLITIK_PEMERINTAHAN
(37/6459) ID: 47016 → BENCANA_LINGKUNGAN
(38/6459) ID: 24123 → EKONOMI_BISNIS
(39/6459) ID: 38675 → EKONOMI_BISNIS
(40/6459) ID: 61801 → EKONOMI_BISNIS
(41/6459) ID: 29841 → EKONOMI_BISNIS
(42/6459) ID: 3775 → HUKUM_KRIMINAL
(43/6459) ID: 52927 → EKONOMI_BISNIS
(44/6459) ID: 6802 → EKONOMI_BISNIS
(45/6459) ID: 23502 → HUKUM_KRIMINAL
(46/6459) ID: 23606 → POLITIK_PEMERINTAHAN
(47/6459) ID: 63383 → EKONOMI_BISNIS
(48/6459) ID: 24348 → EKONOMI_BISNIS
(49/6459) ID: 38952 → POLITIK_PEMERINTAHAN
(50/6459) ID: 63150 → BENCANA_LINGKUNGAN
(51/6459) ID: 35492 → POLITIK_PEMERINTAHAN
(52/6459) ID: 51481 → HUKUM_KRIMINAL
(53/6459) ID: 9423 → EKONOMI_BISNIS
(54/6459) ID: 3681 → EKONOMI_BISNIS
(55/6459) ID: 31773 → HUKUM_KRIMINAL
(56/6459) ID: 43842 → EKONOMI_BISNIS
(57/6459) ID: 47990 → HUKUM_KRIMINAL
(58/6459) ID: 56608 → POLITIK_PEMERINTAHAN
(59/6459) ID: 36479 → POLITIK_PEMERINTAHAN
(60/6459) ID: 40432 → POLITIK_PEMERINTAHAN
(61/6459) ID: 4286 → EKONOMI_BISNIS
(62/6459) ID: 29546 → HUKUM_KRIMINAL
(63/6459) ID: 61453 → HUKUM_KRIMINAL
(64/6459) ID: 59431 → HUKUM_KRIMINAL
(65/6459) ID: 4154 → TEKNOLOGI_DIGITAL
(66/6459) ID: 14519 → POLITIK_PEMERINTAHAN
(67/6459) ID: 46106 → HUKUM_KRIMINAL
(68/6459) ID: 16140 → POLITIK_PEMERINTAHAN
(69/6459) ID: 26053 → POLITIK_PEMERINTAHAN
(70/6459) ID: 38061 → HUKUM_KRIMINAL
(71/6459) ID: 3688 → HUKUM_KRIMINAL
(72/6459) ID: 9067 → HUKUM_KRIMINAL
(73/6459) ID: 9632 → POLITIK_PEMERINTAHAN
(74/6459) ID: 40953 → EKONOMI_BISNIS
(75/6459) ID: 12798 → EKONOMI_BISNIS
(76/6459) ID: 30301 → POLITIK_PEMERINTAHAN
(77/6459) ID: 29597 → HUKUM_KRIMINAL
(78/6459) ID: 10489 → POLITIK_PEMERINTAHAN
(79/6459) ID: 14870 → POLITIK_PEMERINTAHAN
(80/6459) ID: 10215 → POLITIK_PEMERINTAHAN
(81/6459) ID: 175 → OLAHRAGA
(82/6459) ID: 25773 → BENCANA_LINGKUNGAN
(83/6459) ID: 15585 → EKONOMI_BISNIS
(84/6459) ID: 4630 → BENCANA_LINGKUNGAN
(85/6459) ID: 47257 → EKONOMI_BISNIS
(86/6459) ID: 40309 → HUKUM_KRIMINAL
(87/6459) ID: 15446 → POLITIK_PEMERINTAHAN
(88/6459) ID: 14898 → HUKUM_KRIMINAL
(89/6459) ID: 37764 → BENCANA_LINGKUNGAN
(90/6459) ID: 38847 → EKONOMI_BISNIS
(91/6459) ID: 5241 → HUKUM_KRIMINAL
(92/6459) ID: 35366 → HUKUM_KRIMINAL
(93/6459) ID: 60188 → HUKUM_KRIMINAL
(94/6459) ID: 52177 → EKONOMI_BISNIS
(95/6459) ID: 59842 → BENCANA_LINGKUNGAN
(96/6459) ID: 14709 → EKONOMI_BISNIS
(97/6459) ID: 25369 → EKONOMI_BISNIS
(98/6459) ID: 52108 → EKONOMI_BISNIS
(99/6459) ID: 50481 → POLITIK_PEMERINTAHAN
(100/6459) ID: 42146 → EKONOMI_BISNIS
(101/6459) ID: 5340 → BENCANA_LINGKUNGAN
(102/6459) ID: 10900 → HUKUM_KRIMINAL
(103/6459) ID: 29270 → EKONOMI_BISNIS
(104/6459) ID: 62234 → POLITIK_PEMERINTAHAN
(105/6459) ID: 14723 → EKONOMI_BISNIS
(106/6459) ID: 18055 → HUKUM_KRIMINAL
(107/6459) ID: 6729 → EKONOMI_BISNIS
(108/6459) ID: 43691 → EKONOMI_BISNIS
(109/6459) ID: 35900 → POLITIK_PEMERINTAHAN
(110/6459) ID: 4771 → POLITIK_PEMERINTAHAN
(111/6459) ID: 37902 → OLAHRAGA
(112/6459) ID: 37822 → HUKUM_KRIMINAL
(113/6459) ID: 6742 → EKONOMI_BISNIS
(114/6459) ID: 47285 → HUKUM_KRIMINAL
(115/6459) ID: 36578 → HUKUM_KRIMINAL
(116/6459) ID: 50346 → EKONOMI_BISNIS
(117/6459) ID: 29466 → HUKUM_KRIMINAL
(118/6459) ID: 29259 → POLITIK_PEMERINTAHAN
(119/6459) ID: 43636 → BENCANA_LINGKUNGAN
(120/6459) ID: 48695 → BENCANA_LINGKUNGAN
(121/6459) ID: 40027 → HUKUM_KRIMINAL
(122/6459) ID: 47798 → HUKUM_KRIMINAL
(123/6459) ID: 43671 → BENCANA_LINGKUNGAN
(124/6459) ID: 30508 → HUKUM_KRIMINAL
(125/6459) ID: 50777 → HUKUM_KRIMINAL
(126/6459) ID: 312 → POLITIK_PEMERINTAHAN
(127/6459) ID: 19734 → POLITIK_PEMERINTAHAN
(128/6459) ID: 52816 → EKONOMI_BISNIS
(129/6459) ID: 34213 → POLITIK_PEMERINTAHAN
(130/6459) ID: 52792 → HUKUM_KRIMINAL
(131/6459) ID: 48452 → HUKUM_KRIMINAL
(132/6459) ID: 44432 → POLITIK_PEMERINTAHAN
(133/6459) ID: 6583 → EKONOMI_BISNIS
(134/6459) ID: 46884 → POLITIK_PEMERINTAHAN
(135/6459) ID: 47179 → HUKUM_KRIMINAL
(136/6459) ID: 42785 → EKONOMI_BISNIS
(137/6459) ID: 29745 → POLITIK_PEMERINTAHAN
(138/6459) ID: 4300 → HUKUM_KRIMINAL
(139/6459) ID: 24727 → HUKUM_KRIMINAL
(140/6459) ID: 59394 → HUKUM_KRIMINAL
(141/6459) ID: 48273 → HUKUM_KRIMINAL
(142/6459) ID: 26943 → POLITIK_PEMERINTAHAN
(143/6459) ID: 8651 → EKONOMI_BISNIS
(144/6459) ID: 5179 → POLITIK_PEMERINTAHAN
(145/6459) ID: 36574 → POLITIK_PEMERINTAHAN
(146/6459) ID: 52873 → POLITIK_PEMERINTAHAN
(147/6459) ID: 47796 → EKONOMI_BISNIS
(148/6459) ID: 37739 → POLITIK_PEMERINTAHAN
(149/6459) ID: 10174 → POLITIK_PEMERINTAHAN
(150/6459) ID: 22065 → EKONOMI_BISNIS
(151/6459) ID: 6774 → EKONOMI_BISNIS
(152/6459) ID: 53590 → EKONOMI_BISNIS
(153/6459) ID: 52998 → BENCANA_LINGKUNGAN
(154/6459) ID: 59536 → POLITIK_PEMERINTAHAN
(155/6459) ID: 52435 → POLITIK_PEMERINTAHAN
(156/6459) ID: 15433 → POLITIK_PEMERINTAHAN
(157/6459) ID: 53119 → HUKUM_KRIMINAL
(158/6459) ID: 44156 → POLITIK_PEMERINTAHAN
(159/6459) ID: 42759 → EKONOMI_BISNIS
(160/6459) ID: 25167 → EKONOMI_BISNIS
(161/6459) ID: 6762 → OLAHRAGA
(162/6459) ID: 28829 → HUKUM_KRIMINAL
(163/6459) ID: 62280 → TEKNOLOGI_DIGITAL
(164/6459) ID: 38001 → EKONOMI_BISNIS
(165/6459) ID: 49298 → POLITIK_PEMERINTAHAN
(166/6459) ID: 21607 → TEKNOLOGI_DIGITAL
(167/6459) ID: 61665 → POLITIK_PEMERINTAHAN
(168/6459) ID: 45300 → EKONOMI_BISNIS
(169/6459) ID: 29558 → POLITIK_PEMERINTAHAN
(170/6459) ID: 56196 → HUKUM_KRIMINAL
(171/6459) ID: 60219 → OLAHRAGA
(172/6459) ID: 61473 → HUKUM_KRIMINAL
(173/6459) ID: 26271 → HUKUM_KRIMINAL
(174/6459) ID: 24271 → HUKUM_KRIMINAL
(175/6459) ID: 52028 → POLITIK_PEMERINTAHAN
(176/6459) ID: 14688 → EKONOMI_BISNIS
(177/6459) ID: 52419 → BENCANA_LINGKUNGAN
(178/6459) ID: 33841 → EKONOMI_BISNIS
(179/6459) ID: 40117 → EKONOMI_BISNIS
(180/6459) ID: 62335 → POLITIK_PEMERINTAHAN
(181/6459) ID: 11096 → OLAHRAGA
(182/6459) ID: 4191 → HUKUM_KRIMINAL
(183/6459) ID: 44113 → EKONOMI_BISNIS
(184/6459) ID: 60164 → HUKUM_KRIMINAL
(185/6459) ID: 44079 → TEKNOLOGI_DIGITAL
(186/6459) ID: 62800 → HUKUM_KRIMINAL
(187/6459) ID: 6941 → HUKUM_KRIMINAL
(188/6459) ID: 34628 → EKONOMI_BISNIS
(189/6459) ID: 13089 → POLITIK_PEMERINTAHAN
(190/6459) ID: 63071 → POLITIK_PEMERINTAHAN
(191/6459) ID: 23262 → HUKUM_KRIMINAL
(192/6459) ID: 10231 → HUKUM_KRIMINAL
(193/6459) ID: 6463 → HUKUM_KRIMINAL
(194/6459) ID: 38039 → POLITIK_PEMERINTAHAN
(195/6459) ID: 6776 → POLITIK_PEMERINTAHAN
(196/6459) ID: 60625 → POLITIK_PEMERINTAHAN
(197/6459) ID: 9820 → POLITIK_PEMERINTAHAN
(198/6459) ID: 14767 → POLITIK_PEMERINTAHAN
(199/6459) ID: 43299 → BENCANA_LINGKUNGAN
(200/6459) ID: 61339 → POLITIK_PEMERINTAHAN
(201/6459) ID: 30646 → HUKUM_KRIMINAL
(202/6459) ID: 14801 → POLITIK_PEMERINTAHAN
(203/6459) ID: 8954 → POLITIK_PEMERINTAHAN
(204/6459) ID: 52467 → EKONOMI_BISNIS
(205/6459) ID: 58675 → EKONOMI_BISNIS
(206/6459) ID: 13134 → POLITIK_PEMERINTAHAN
(207/6459) ID: 39870 → POLITIK_PEMERINTAHAN
(208/6459) ID: 60420 → POLITIK_PEMERINTAHAN
(209/6459) ID: 50145 → POLITIK_PEMERINTAHAN
(210/6459) ID: 6851 → POLITIK_PEMERINTAHAN
(211/6459) ID: 32095 → OLAHRAGA
(212/6459) ID: 27452 → EKONOMI_BISNIS
(213/6459) ID: 38222 → BENCANA_LINGKUNGAN
(214/6459) ID: 60903 → OLAHRAGA
(215/6459) ID: 24242 → EKONOMI_BISNIS
(216/6459) ID: 14528 → POLITIK_PEMERINTAHAN
(217/6459) ID: 16947 → POLITIK_PEMERINTAHAN
(218/6459) ID: 21275 → POLITIK_PEMERINTAHAN
(219/6459) ID: 21220 → POLITIK_PEMERINTAHAN
(220/6459) ID: 37914 → POLITIK_PEMERINTAHAN
(221/6459) ID: 5912 → HUKUM_KRIMINAL
(222/6459) ID: 31945 → OLAHRAGA
(223/6459) ID: 34864 → EKONOMI_BISNIS
(224/6459) ID: 63337 → EKONOMI_BISNIS
(225/6459) ID: 11014 → HUKUM_KRIMINAL
(226/6459) ID: 12900 → EKONOMI_BISNIS
(227/6459) ID: 22400 → OLAHRAGA
(228/6459) ID: 58878 → EKONOMI_BISNIS
(229/6459) ID: 52906 → EKONOMI_BISNIS
(230/6459) ID: 16102 → POLITIK_PEMERINTAHAN
(231/6459) ID: 53123 → OLAHRAGA
(232/6459) ID: 41978 → HUKUM_KRIMINAL
(233/6459) ID: 59533 → OLAHRAGA
(234/6459) ID: 25867 → HUKUM_KRIMINAL
(235/6459) ID: 10049 → EKONOMI_BISNIS
(236/6459) ID: 42028 → EKONOMI_BISNIS
(237/6459) ID: 26985 → BENCANA_LINGKUNGAN
(238/6459) ID: 25951 → HUKUM_KRIMINAL
(239/6459) ID: 43687 → POLITIK_PEMERINTAHAN
(240/6459) ID: 38653 → POLITIK_PEMERINTAHAN
(241/6459) ID: 39181 → EKONOMI_BISNIS
(242/6459) ID: 34079 → POLITIK_PEMERINTAHAN
(243/6459) ID: 51700 → EKONOMI_BISNIS
(244/6459) ID: 47810 → EKONOMI_BISNIS
(245/6459) ID: 53079 → HUKUM_KRIMINAL
(246/6459) ID: 32280 → EKONOMI_BISNIS
(247/6459) ID: 7551 → HUKUM_KRIMINAL
(248/6459) ID: 62337 → POLITIK_PEMERINTAHAN
(249/6459) ID: 4138 → EKONOMI_BISNIS
(250/6459) ID: 37205 → BENCANA_LINGKUNGAN
(251/6459) ID: 46813 → HUKUM_KRIMINAL
(252/6459) ID: 22104 → BENCANA_LINGKUNGAN
(253/6459) ID: 40242 → POLITIK_PEMERINTAHAN
(254/6459) ID: 32642 → POLITIK_PEMERINTAHAN
(255/6459) ID: 16544 → POLITIK_PEMERINTAHAN
(256/6459) ID: 23496 → POLITIK_PEMERINTAHAN
(257/6459) ID: 51189 → EKONOMI_BISNIS
(258/6459) ID: 62316 → POLITIK_PEMERINTAHAN
(259/6459) ID: 50520 → HUKUM_KRIMINAL
(260/6459) ID: 36824 → POLITIK_PEMERINTAHAN
(261/6459) ID: 7026 → HUKUM_KRIMINAL
(262/6459) ID: 14338 → EKONOMI_BISNIS
(263/6459) ID: 61456 → HUKUM_KRIMINAL
(264/6459) ID: 63074 → HUKUM_KRIMINAL
(265/6459) ID: 24141 → HUKUM_KRIMINAL
(266/6459) ID: 32309 → HUKUM_KRIMINAL
(267/6459) ID: 28025 → EKONOMI_BISNIS
(268/6459) ID: 37726 → HUKUM_KRIMINAL
(269/6459) ID: 14270 → EKONOMI_BISNIS
(270/6459) ID: 23838 → POLITIK_PEMERINTAHAN
(271/6459) ID: 47116 → POLITIK_PEMERINTAHAN
(272/6459) ID: 45035 → POLITIK_PEMERINTAHAN
(273/6459) ID: 31674 → HUKUM_KRIMINAL
(274/6459) ID: 7087 → POLITIK_PEMERINTAHAN
(275/6459) ID: 35361 → BENCANA_LINGKUNGAN
(276/6459) ID: 47987 → POLITIK_PEMERINTAHAN
(277/6459) ID: 34606 → POLITIK_PEMERINTAHAN
(278/6459) ID: 46472 → EKONOMI_BISNIS
(279/6459) ID: 28585 → POLITIK_PEMERINTAHAN
(280/6459) ID: 53446 → POLITIK_PEMERINTAHAN
(281/6459) ID: 38773 → BENCANA_LINGKUNGAN
(282/6459) ID: 57741 → BENCANA_LINGKUNGAN
(283/6459) ID: 26639 → EKONOMI_BISNIS
(284/6459) ID: 18106 → TEKNOLOGI_DIGITAL
(285/6459) ID: 60746 → HUKUM_KRIMINAL
(286/6459) ID: 19830 → EKONOMI_BISNIS
(287/6459) ID: 240 → HUKUM_KRIMINAL
(288/6459) ID: 59571 → BENCANA_LINGKUNGAN
(289/6459) ID: 55022 → POLITIK_PEMERINTAHAN
(290/6459) ID: 34796 → EKONOMI_BISNIS
(291/6459) ID: 51694 → OLAHRAGA
(292/6459) ID: 60406 → OLAHRAGA
(293/6459) ID: 60632 → EKONOMI_BISNIS
(294/6459) ID: 61867 → EKONOMI_BISNIS
(295/6459) ID: 37484 → EKONOMI_BISNIS
(296/6459) ID: 36765 → EKONOMI_BISNIS
(297/6459) ID: 17737 → EKONOMI_BISNIS
(298/6459) ID: 36924 → POLITIK_PEMERINTAHAN
(299/6459) ID: 50113 → EKONOMI_BISNIS
(300/6459) ID: 46301 → EKONOMI_BISNIS
(301/6459) ID: 9599 → HUKUM_KRIMINAL
(302/6459) ID: 9430 → EKONOMI_BISNIS
(303/6459) ID: 23605 → HUKUM_KRIMINAL
(304/6459) ID: 38120 → POLITIK_PEMERINTAHAN
(305/6459) ID: 46289 → HUKUM_KRIMINAL
(306/6459) ID: 26842 → POLITIK_PEMERINTAHAN
(307/6459) ID: 22271 → HUKUM_KRIMINAL
(308/6459) ID: 50994 → EKONOMI_BISNIS
(309/6459) ID: 61856 → EKONOMI_BISNIS
(310/6459) ID: 43762 → EKONOMI_BISNIS
(311/6459) ID: 56577 → OLAHRAGA
(312/6459) ID: 35653 → HUKUM_KRIMINAL
(313/6459) ID: 14577 → HUKUM_KRIMINAL
(314/6459) ID: 12509 → EKONOMI_BISNIS
(315/6459) ID: 21769 → EKONOMI_BISNIS
(316/6459) ID: 25435 → POLITIK_PEMERINTAHAN
(317/6459) ID: 47052 → EKONOMI_BISNIS
(318/6459) ID: 15957 → EKONOMI_BISNIS
(319/6459) ID: 18271 → POLITIK_PEMERINTAHAN
(320/6459) ID: 57198 → POLITIK_PEMERINTAHAN
(321/6459) ID: 45522 → EKONOMI_BISNIS
(322/6459) ID: 59714 → HUKUM_KRIMINAL
(323/6459) ID: 29548 → HUKUM_KRIMINAL
(324/6459) ID: 45538 → POLITIK_PEMERINTAHAN
(325/6459) ID: 53564 → HUKUM_KRIMINAL
(326/6459) ID: 9630 → HUKUM_KRIMINAL
(327/6459) ID: 46261 → EKONOMI_BISNIS
(328/6459) ID: 11637 → EKONOMI_BISNIS
(329/6459) ID: 35939 → POLITIK_PEMERINTAHAN
(330/6459) ID: 44520 → POLITIK_PEMERINTAHAN
(331/6459) ID: 288 → BENCANA_LINGKUNGAN
(332/6459) ID: 28891 → EKONOMI_BISNIS
(333/6459) ID: 40855 → EKONOMI_BISNIS
(334/6459) ID: 28887 → EKONOMI_BISNIS
(335/6459) ID: 43891 → EKONOMI_BISNIS
(336/6459) ID: 44844 → POLITIK_PEMERINTAHAN
(337/6459) ID: 30724 → EKONOMI_BISNIS
(338/6459) ID: 60168 → POLITIK_PEMERINTAHAN
(339/6459) ID: 50350 → POLITIK_PEMERINTAHAN
(340/6459) ID: 58280 → POLITIK_PEMERINTAHAN
(341/6459) ID: 21589 → OLAHRAGA
(342/6459) ID: 40548 → BENCANA_LINGKUNGAN
(343/6459) ID: 16955 → BENCANA_LINGKUNGAN
(344/6459) ID: 60844 → HUKUM_KRIMINAL
(345/6459) ID: 53688 → HUKUM_KRIMINAL
(346/6459) ID: 56715 → POLITIK_PEMERINTAHAN
(347/6459) ID: 46462 → POLITIK_PEMERINTAHAN
(348/6459) ID: 18959 → EKONOMI_BISNIS
(349/6459) ID: 37365 → HUKUM_KRIMINAL
(350/6459) ID: 32536 → POLITIK_PEMERINTAHAN
(351/6459) ID: 16756 → EKONOMI_BISNIS
(352/6459) ID: 11083 → OLAHRAGA
(353/6459) ID: 52288 → EKONOMI_BISNIS
(354/6459) ID: 61582 → HUKUM_KRIMINAL
(355/6459) ID: 5132 → POLITIK_PEMERINTAHAN
(356/6459) ID: 53921 → EKONOMI_BISNIS
(357/6459) ID: 36389 → HUKUM_KRIMINAL
(358/6459) ID: 43959 → BENCANA_LINGKUNGAN
(359/6459) ID: 33874 → EKONOMI_BISNIS
(360/6459) ID: 9613 → HUKUM_KRIMINAL
(361/6459) ID: 42652 → HUKUM_KRIMINAL
(362/6459) ID: 48207 → POLITIK_PEMERINTAHAN
(363/6459) ID: 50081 → EKONOMI_BISNIS
(364/6459) ID: 348 → EKONOMI_BISNIS
(365/6459) ID: 48437 → EKONOMI_BISNIS
(366/6459) ID: 10403 → POLITIK_PEMERINTAHAN
(367/6459) ID: 25629 → POLITIK_PEMERINTAHAN
(368/6459) ID: 28968 → EKONOMI_BISNIS
(369/6459) ID: 24216 → POLITIK_PEMERINTAHAN
(370/6459) ID: 12480 → POLITIK_PEMERINTAHAN
(371/6459) ID: 60497 → POLITIK_PEMERINTAHAN
(372/6459) ID: 59588 → EKONOMI_BISNIS
(373/6459) ID: 35394 → HUKUM_KRIMINAL
(374/6459) ID: 46238 → POLITIK_PEMERINTAHAN
(375/6459) ID: 44301 → EKONOMI_BISNIS
(376/6459) ID: 46818 → POLITIK_PEMERINTAHAN
(377/6459) ID: 60932 → EKONOMI_BISNIS
(378/6459) ID: 10054 → EKONOMI_BISNIS
(379/6459) ID: 18731 → EKONOMI_BISNIS
(380/6459) ID: 50407 → EKONOMI_BISNIS
(381/6459) ID: 7637 → EKONOMI_BISNIS
(382/6459) ID: 59638 → EKONOMI_BISNIS
(383/6459) ID: 5265 → BENCANA_LINGKUNGAN
(384/6459) ID: 51709 → EKONOMI_BISNIS
(385/6459) ID: 50564 → EKONOMI_BISNIS
(386/6459) ID: 45008 → EKONOMI_BISNIS
(387/6459) ID: 32076 → POLITIK_PEMERINTAHAN
(388/6459) ID: 10458 → POLITIK_PEMERINTAHAN
(389/6459) ID: 6932 → EKONOMI_BISNIS
(390/6459) ID: 20003 → POLITIK_PEMERINTAHAN
(391/6459) ID: 32500 → OLAHRAGA
(392/6459) ID: 22866 → OLAHRAGA
(393/6459) ID: 48949 → EKONOMI_BISNIS
(394/6459) ID: 23879 → OLAHRAGA
(395/6459) ID: 62390 → HUKUM_KRIMINAL
(396/6459) ID: 62015 → EKONOMI_BISNIS
(397/6459) ID: 6995 → POLITIK_PEMERINTAHAN
(398/6459) ID: 9985 → POLITIK_PEMERINTAHAN
(399/6459) ID: 15003 → POLITIK_PEMERINTAHAN
(400/6459) ID: 40163 → EKONOMI_BISNIS
(401/6459) ID: 39232 → OLAHRAGA
(402/6459) ID: 29072 → EKONOMI_BISNIS
(403/6459) ID: 50782 → HUKUM_KRIMINAL
(404/6459) ID: 23997 → OLAHRAGA
(405/6459) ID: 15553 → EKONOMI_BISNIS
(406/6459) ID: 12035 → HUKUM_KRIMINAL
(407/6459) ID: 57856 → POLITIK_PEMERINTAHAN
(408/6459) ID: 24227 → TEKNOLOGI_DIGITAL
(409/6459) ID: 35570 → EKONOMI_BISNIS
(410/6459) ID: 19461 → BENCANA_LINGKUNGAN
(411/6459) ID: 53340 → POLITIK_PEMERINTAHAN(412/6459) ID: 60899 → OLAHRAGA

(413/6459) ID: 9609 → HUKUM_KRIMINAL
(414/6459) ID: 38197 → POLITIK_PEMERINTAHAN
(415/6459) ID: 7877 → HUKUM_KRIMINAL
(416/6459) ID: 33838 → TEKNOLOGI_DIGITAL
(417/6459) ID: 53357 → BENCANA_LINGKUNGAN
(418/6459) ID: 56091 → POLITIK_PEMERINTAHAN
(419/6459) ID: 22521 → POLITIK_PEMERINTAHAN
(420/6459) ID: 29924 → POLITIK_PEMERINTAHAN
(421/6459) ID: 52067 → POLITIK_PEMERINTAHAN
(422/6459) ID: 6760 → EKONOMI_BISNIS
(423/6459) ID: 17955 → HUKUM_KRIMINAL
(424/6459) ID: 60889 → EKONOMI_BISNIS
(425/6459) ID: 8504 → POLITIK_PEMERINTAHAN
(426/6459) ID: 45459 → EKONOMI_BISNIS
(427/6459) ID: 6212 → POLITIK_PEMERINTAHAN
(428/6459) ID: 40277 → TEKNOLOGI_DIGITAL
(429/6459) ID: 15121 → EKONOMI_BISNIS
(430/6459) ID: 40430 → TEKNOLOGI_DIGITAL
(431/6459) ID: 18805 → OLAHRAGA
(432/6459) ID: 47133 → POLITIK_PEMERINTAHAN
(433/6459) ID: 12065 → POLITIK_PEMERINTAHAN
(434/6459) ID: 49987 → EKONOMI_BISNIS
(435/6459) ID: 30604 → POLITIK_PEMERINTAHAN
(436/6459) ID: 48897 → EKONOMI_BISNIS
(437/6459) ID: 59964 → BENCANA_LINGKUNGAN
(438/6459) ID: 59780 → BENCANA_LINGKUNGAN
(439/6459) ID: 35483 → BENCANA_LINGKUNGAN
(440/6459) ID: 35868 → HUKUM_KRIMINAL
(441/6459) ID: 13195 → POLITIK_PEMERINTAHAN
(442/6459) ID: 10524 → HUKUM_KRIMINAL
(443/6459) ID: 29591 → HUKUM_KRIMINAL
(444/6459) ID: 61548 → HUKUM_KRIMINAL
(445/6459) ID: 50202 → HUKUM_KRIMINAL
(446/6459) ID: 4353 → HUKUM_KRIMINAL
(447/6459) ID: 24968 → POLITIK_PEMERINTAHAN
(448/6459) ID: 35641 → POLITIK_PEMERINTAHAN
(449/6459) ID: 40584 → POLITIK_PEMERINTAHAN
(450/6459) ID: 4128 → EKONOMI_BISNIS
(451/6459) ID: 25679 → POLITIK_PEMERINTAHAN
(452/6459) ID: 53129 → POLITIK_PEMERINTAHAN
(453/6459) ID: 42620 → HUKUM_KRIMINAL
(454/6459) ID: 62918 → POLITIK_PEMERINTAHAN
(455/6459) ID: 47663 → POLITIK_PEMERINTAHAN
(456/6459) ID: 13928 → OLAHRAGA
(457/6459) ID: 46826 → HUKUM_KRIMINAL
(458/6459) ID: 37311 → EKONOMI_BISNIS
(459/6459) ID: 46738 → EKONOMI_BISNIS
(460/6459) ID: 25712 → POLITIK_PEMERINTAHAN
(461/6459) ID: 10339 → POLITIK_PEMERINTAHAN
(462/6459) ID: 53060 → OLAHRAGA
(463/6459) ID: 10079 → EKONOMI_BISNIS
(464/6459) ID: 50992 → OLAHRAGA
(465/6459) ID: 23755 → HUKUM_KRIMINAL
(466/6459) ID: 10845 → EKONOMI_BISNIS
(467/6459) ID: 33119 → BENCANA_LINGKUNGAN
(468/6459) ID: 23363 → POLITIK_PEMERINTAHAN
(469/6459) ID: 45338 → BENCANA_LINGKUNGAN
(470/6459) ID: 5137 → BENCANA_LINGKUNGAN
(471/6459) ID: 52801 → POLITIK_PEMERINTAHAN
(472/6459) ID: 36782 → HUKUM_KRIMINAL
(473/6459) ID: 44577 → EKONOMI_BISNIS
(474/6459) ID: 59925 → BENCANA_LINGKUNGAN
(475/6459) ID: 59895 → HUKUM_KRIMINAL
(476/6459) ID: 60713 → HUKUM_KRIMINAL
(477/6459) ID: 34694 → EKONOMI_BISNIS
(478/6459) ID: 46985 → HUKUM_KRIMINAL
(479/6459) ID: 38382 → POLITIK_PEMERINTAHAN
(480/6459) ID: 50022 → HUKUM_KRIMINAL
(481/6459) ID: 5579 → EKONOMI_BISNIS
(482/6459) ID: 44088 → HUKUM_KRIMINAL(483/6459) ID: 12755 → BENCANA_LINGKUNGAN

(484/6459) ID: 35887 → TEKNOLOGI_DIGITAL
(485/6459) ID: 18724 → EKONOMI_BISNIS
(486/6459) ID: 55828 → EKONOMI_BISNIS
(487/6459) ID: 21266 → POLITIK_PEMERINTAHAN
(488/6459) ID: 15951 → EKONOMI_BISNIS
(489/6459) ID: 29207 → EKONOMI_BISNIS
(490/6459) ID: 40887 → POLITIK_PEMERINTAHAN
(491/6459) ID: 22592 → HUKUM_KRIMINAL
(492/6459) ID: 24224 → OLAHRAGA
(493/6459) ID: 37611 → HUKUM_KRIMINAL
(494/6459) ID: 24622 → EKONOMI_BISNIS
(495/6459) ID: 40143 → HUKUM_KRIMINAL
(496/6459) ID: 39005 → EKONOMI_BISNIS
(497/6459) ID: 16790 → HUKUM_KRIMINAL
(498/6459) ID: 17145 → POLITIK_PEMERINTAHAN
(499/6459) ID: 28661 → BENCANA_LINGKUNGAN
(500/6459) ID: 12383 → EKONOMI_BISNIS
(501/6459) ID: 25608 → POLITIK_PEMERINTAHAN
(502/6459) ID: 29290 → EKONOMI_BISNIS
(503/6459) ID: 52576 → EKONOMI_BISNIS
(504/6459) ID: 36394 → HUKUM_KRIMINAL
(505/6459) ID: 59007 → BENCANA_LINGKUNGAN
(506/6459) ID: 36320 → EKONOMI_BISNIS

In [136]:
import pandas as pd

df_result = pd.DataFrame(results)
df_result.to_csv("hasil_klasifikasi_news.csv", index=False)

total = len(df_result)
sukses = df_result["predicted_label"].notna().sum()
error = df_result["error"].notna().sum()
akurasi = (df_result["label"] == df_result["predicted_label"]).mean() * 100

print(f"Total   : {total}")
print(f"Sukses  : {sukses}")
print(f"Error   : {error}")
print(f"Akurasi : {akurasi:.2f}%")
print(f"File    : hasil_klasifikasi_news.csv")

Total   : 6459
Sukses  : 6459
Error   : 0
Akurasi : 83.34%
File    : hasil_klasifikasi_news.csv

In [137]:
df = pd.read_csv("hasil_klasifikasi_news.csv")
label_percentage = df["label"].value_counts(normalize=True) * 100
print("Distribusi Label (%):")
print(label_percentage.round(2))

Distribusi Label (%):
label
POLITIK_PEMERINTAHAN    30.78
HUKUM_KRIMINAL          27.33
EKONOMI_BISNIS          26.58
BENCANA_LINGKUNGAN       8.28
OLAHRAGA                 4.77
TEKNOLOGI_DIGITAL        2.26
Name: proportion, dtype: float64

In [138]:
predicted_percentage = df["predicted_label"].value_counts(normalize=True) * 100
print("Distribusi Predicted Label (%):")
print(predicted_percentage.round(2))

Distribusi Predicted Label (%):
predicted_label
POLITIK_PEMERINTAHAN    30.08
EKONOMI_BISNIS          27.14
HUKUM_KRIMINAL          25.56
BENCANA_LINGKUNGAN       8.92
OLAHRAGA                 6.12
TEKNOLOGI_DIGITAL        2.18
Name: proportion, dtype: float64

In [139]:
summary = pd.DataFrame({
    "Label (n)": df_result["label"].value_counts(),
    "Predicted (n)": df_result["predicted_label"].value_counts(),
    "Label (%)": df_result["label"].value_counts(normalize=True) * 100,
    "Predicted (%)": df_result["predicted_label"].value_counts(normalize=True) * 100,
}).fillna(0).round(2)

summary["Gap (%)"] = (summary["Predicted (%)"] - summary["Label (%)"]).round(2)
summary["Gap (n)"] = (summary["Predicted (n)"] - summary["Label (n)"]).astype(int)
summary = summary.sort_values("Label (%)", ascending=False)

total_row = pd.DataFrame({
    "Label (%)": [summary["Label (%)"].sum()],
    "Predicted (%)": [summary["Predicted (%)"].sum()],
    "Label (n)": [summary["Label (n)"].sum()],
    "Predicted (n)": [summary["Predicted (n)"].sum()],
    "Gap (%)": [summary["Gap (%)"].abs().sum().round(2)],
    "Gap (n)": [summary["Gap (n)"].abs().sum()]
}, index=["TOTAL"])

summary = pd.concat([summary, total_row])

summary[["Label (n)", "Predicted (n)", "Gap (n)"]] = summary[["Label (n)", "Predicted (n)", "Gap (n)"]].astype(int)

summary.style.background_gradient(cmap="RdYlGn_r", subset=["Gap (%)", "Gap (n)"])

In [140]:
# Filter data yang salah prediksi
df_errors = df_result[df_result["label"] != df_result["predicted_label"]].copy()

print(f"Total salah prediksi: {len(df_errors)} dari {len(df_result)} ({len(df_errors)/len(df_result)*100:.2f}%)")
print(f"Total benar prediksi: {len(df_result) - len(df_errors)}\n")

# Tampilkan pasangan error terbanyak
error_pairs = (
    df_errors.groupby(["label", "predicted_label"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)

print("Top misclassification pairs:")
display(error_pairs)

Total salah prediksi: 1076 dari 6459 (16.66%)
Total benar prediksi: 5383

Top misclassification pairs:

                   label       predicted_label  count
8         EKONOMI_BISNIS  POLITIK_PEMERINTAHAN    153
21  POLITIK_PEMERINTAHAN        EKONOMI_BISNIS    143
13        HUKUM_KRIMINAL  POLITIK_PEMERINTAHAN    128
23  POLITIK_PEMERINTAHAN              OLAHRAGA     96
20  POLITIK_PEMERINTAHAN    BENCANA_LINGKUNGAN     73
22  POLITIK_PEMERINTAHAN        HUKUM_KRIMINAL     70
0     BENCANA_LINGKUNGAN        EKONOMI_BISNIS     53
10        HUKUM_KRIMINAL    BENCANA_LINGKUNGAN     49
18              OLAHRAGA  POLITIK_PEMERINTAHAN     46
9         EKONOMI_BISNIS     TEKNOLOGI_DIGITAL     42
26     TEKNOLOGI_DIGITAL        EKONOMI_BISNIS     30
28     TEKNOLOGI_DIGITAL              OLAHRAGA     25
11        HUKUM_KRIMINAL        EKONOMI_BISNIS     23
16              OLAHRAGA        EKONOMI_BISNIS     17
2     BENCANA_LINGKUNGAN              OLAHRAGA     17
7         EKONOMI_BISNIS              OLAHRAGA     16
3     BENCANA_LINGKUNGAN  POLITIK_PEMERINTAHAN     15
6         EKONOMI_BISNIS        HUKUM_KRIMINAL     14
1     BENCANA_LINGKUNGAN        HUKUM_KRIMINAL     10
24  POLITIK_PEMERINTAHAN     TEKNOLOGI_DIGITAL      9
15              OLAHRAGA    BENCANA_LINGKUNGAN      9
12        HUKUM_KRIMINAL              OLAHRAGA      7
14        HUKUM_KRIMINAL     TEKNOLOGI_DIGITAL      6
25     TEKNOLOGI_DIGITAL    BENCANA_LINGKUNGAN      5
5         EKONOMI_BISNIS    BENCANA_LINGKUNGAN      5
4     BENCANA_LINGKUNGAN     TEKNOLOGI_DIGITAL      5
27     TEKNOLOGI_DIGITAL        HUKUM_KRIMINAL      4
29     TEKNOLOGI_DIGITAL  POLITIK_PEMERINTAHAN      4
19              OLAHRAGA     TEKNOLOGI_DIGITAL      1
17              OLAHRAGA        HUKUM_KRIMINAL      1

In [ ]:
# Load dataset asli untuk ambil title dan content
from datasets import load_dataset

raw_dataset = load_dataset(
    "fahadh4ilyas/indonesian_news_datasets",
    split="test",
    token="hf_xxxxxxxxxxxx"
)

df_raw = pd.DataFrame(raw_dataset)

# Merge dengan hasil prediksi
df_merged = df_result.merge(df_raw[["id", "title", "content"]], on="id", how="left")

# Filter yang salah
df_errors = df_merged[df_merged["label"] != df_merged["predicted_label"]].copy()

print(f"Total salah prediksi: {len(df_errors)} dari {len(df_merged)}")
print(f"Kolom tersedia: {df_errors.columns.tolist()}")

Total salah prediksi: 1076 dari 6459
Kolom tersedia: ['id', 'label', 'predicted_label', 'response_id', 'error', 'title', 'content']

In [142]:
# Investigasi per pasangan
target_ids = {
    ("EKONOMI_BISNIS", "POLITIK_PEMERINTAHAN"): [14870, 10489, 61665],
    ("POLITIK_PEMERINTAHAN", "EKONOMI_BISNIS"): [3769, 37597, 30899],
    ("HUKUM_KRIMINAL", "POLITIK_PEMERINTAHAN"): [26053, 5179, 38039],
    ("POLITIK_PEMERINTAHAN", "OLAHRAGA"): [60219, 56577, 11083],
    ("POLITIK_PEMERINTAHAN", "HUKUM_KRIMINAL"): [30508, 60164],
}

pd.set_option("display.max_colwidth", 500)

for (true_label, pred_label), ids in target_ids.items():
    print(f"\n{'='*60}")
    print(f"TRUE: {true_label} → PREDICTED: {pred_label}")
    print('='*60)

    df_sample = df_errors[df_errors["id"].isin(ids)][["id", "label", "predicted_label", "title", "content"]]
    
    for _, row in df_sample.iterrows():
        print(f"\nID    : {row['id']}")
        print(f"TITLE : {row['title']}")
        print(f"CONTENT: {str(row['content'])[:500]}")
        print("-" * 40)

============================================================
TRUE: EKONOMI_BISNIS → PREDICTED: POLITIK_PEMERINTAHAN
============================================================

ID    : 14870
TITLE : Kemendagri Beri APBD Award 2023 pada Daerah dengan Realisasi APBD Tertinggi
CONTENT: Suara.com - Direktur Jenderal (Dirjen) Bina Keuangan Daerah (Keuda) Kemendagri Agus Fatoni mengatakan, APBD Award 2023 diberikan kepada kepala daerah dengan tiga kategori. Pertama, daerah dengan realisasi pendapatan tertinggi. Kedua, daerah dengan realisasi belanja tertinggi. Ketiga, daerah dengan realisasi peningkatan Pendapatan Asli Daerah (PAD) tertinggi. Masing-masing kategori penghargaan tersebut diberikan kepada lima provinsi, lima kabupaten, dan lima kota. "Penilaian didasarkan dari perhi
----------------------------------------

ID    : 10489
TITLE : Salurkan 21 Juta Beras untuk Bansos Lebaran, Bulog Tunggu Data dari Kemensos
CONTENT: TEMPO.CO, Jakarta -Perusahaan Umum atau Perum Bulog menunggu data dari Kementerian Sosial atau Kemensos untuk menyalurkan beras yang menjadi bantuan sosial atau bansos Lebaran.Hal ini diungkap Direktur Bisnis Perum Bulog Febby Novita. Dia mengatakan sudah ada perintah dari Presiden Joko Widodo. Selain itu, sudah ada surat dari Badan Pangan Nasional atau Bapanas untuk penugasan penyediaan beras bansos pangan menjelang Lebaran.Bansos akan dibagikan tiga bulan menjelang Lebaran, yakni Maret, April,
----------------------------------------

ID    : 61665
TITLE : Anak Buah Erick Respons Soal Hasil Audit BPKP Tak Restui Impor KRL
CONTENT: Staf Khusus Menteri BUMN Arya Sinulingga buka suara soal hasil audit Badan Pengawasan Keuangan dan Pembangunan ( BPKP ) yang secara garis besar tidak merekomendasikan impor KRL bekas dari Jepang. Imbas hal itu, Kementerian Koordinator Kemaritiman dan Investasi memastikan pemerintah belum mau menuruti keinginan PT KCI untuk mengimpor KRL bekas Jepang guna memenuhi kebutuhan armada yang akan dipensiunkan. Arya mengatakan saat ini pihaknya masih mendiskusikan hal-hal yang menjadi kebutuhan. Pihakny
----------------------------------------

============================================================
TRUE: POLITIK_PEMERINTAHAN → PREDICTED: EKONOMI_BISNIS
============================================================

ID    : 3769
TITLE : Sidak di Kantor Pajak Solo, Jokowi Pamer Setor SPT Lebih Awal
CONTENT: Presiden JokoWidodo( Jokowi )melakukan inspeksi mendadak (sidak) ke Kantor Pelayanan Pajak (KPP) Pratama Kota Solo , Jawa Tengah, Kamis (9/3). Ia mengecek pelaporan Surat Pemberitahuan Tahunan (SPT) Pajak di kota asalnya itu. Sidak dilakukan Jokowi bersama Menteri Keuangan Sri Mulyani, Sekretaris Kabinet Pramono Anung dan Wakil Wali Kota Solo, Teguh Prakosa. Rombongan tiba di KPP Pratama Kota Solo sekitar pukul 15.30 WIB. Pada kesempatan tersebut, Presiden Jokowi memamerkan dirinya telah mengemb
----------------------------------------

ID    : 37597
TITLE : Kemenkeu Siap Buat Pandemic Fund Versi Asean
CONTENT: Setelah berhasil menginisiasi Pandemic Fund global di G20, Kementerian Keuangan ( ) berencana untuk membuat hal yang sama di . Pandemic Fund merupakan merupakan instrumen untuk mempersiapkan dan merespons pandemi berikutnya dengan lebih baik. Hal ini juga akan dibawa dalam pembahasan pertemuan pertama seluruh bank sentral dan menteri keuangan di ASEAN (AFMGM) yang digelar di Bali 28-31 Maret 2022. Kepala Badan Kebijakan Fiskal (BKF) Kemenkeu, Febrio Nathan Kacaribu mengatakan, pembentukan Pandem
----------------------------------------

ID    : 30899
TITLE : 5 Fakta Bika Ambon Dilarang Masuk Pesawat, Begini Penjelasan Garuda Indonesia
CONTENT: JAKARTA - Ramai di media sosial penumpang pesawat adu mulut dengan petugas di bandara karena membawa 3 kotak Bika Ambon . Dalam video yang beredar, perselisihan terjadi karena penumpang tersebut tidak terima kalau dirinya didenda Rp2 juta hanya karena membawa Bika Ambon. Namun apakah benar membawa Bika Ambon masuk pesawat akan terkena denda?  Dirangkum Okezone, Sabtu (25/3/2023), berikut fakta-fakta penjelasan Garuda Indonesia terkait Bika Ambon dilarang masuk pesawat. 1. Kejadian tahun 2021  Di
----------------------------------------

============================================================
TRUE: HUKUM_KRIMINAL → PREDICTED: POLITIK_PEMERINTAHAN
============================================================

ID    : 26053
TITLE : Kepala PPATK Luruskan Anggapan Publik soal Transaksi TPPU Ratusan Triliun Ada di Kemenkeu
CONTENT: Suara.com - Kepala Pusat Pelaporan dan Analisis Transaksi Keuangan ( PPATK ) Ivan Yustiavandana menjelaskan, transaksi mencurigakan terkait Tindak Pidana Pencucian Uang ( TPPU ) Rp300 triliun yang kini bertambah menjadi Rp 349 triliun. Ivan secara spesifik memberikan menyebut, TPPU bukan terjadi di Kementerian Keuangan ( Kemenkeu ). "Bukan di Kemenkeu. Tapi terkait dengan tugas pokok dan fungsi Kemenkeu, sebagai penyidik tindak pidana asal. Itu kebanyakan, terkait dengan kasus impor ekspor, kasu
----------------------------------------

ID    : 5179
TITLE : Tak Ada Pasukan Tambahan TNI-Polri untuk Pembebasan Pilot Susi Air
CONTENT: Danrem 172 PWY Brigjen TNI JO Sembiring menjelaskan tidak ada penambahan pasukan buat membebaskan pilot Susi Air, Philip Mark Mehrtens, yang kini disandera kelompok kriminal bersenjata (KKB) pimpinan Egianus Kogoya. Mehrtens sudah lebih dari sebulan disandera usai Egianus menyerbu dan membakar pesawatnya di Bandara Paro, Nduga, Papua pada 7 Februari. "Kami lebih memberdayakan prajurit yang ada saat ini," katanya, diberitakan Antara , Sabtu (11/3). Dia menjelaskan sebelumnya sudah ada penambahan
----------------------------------------

ID    : 38039
TITLE : Diperintah Jokowi, Mahfud MD Akan Jelaskan Transaksi Rp 349 Triliun ke DPR
CONTENT: Suara.com - Presiden Joko Widodo atau Jokowi memerintahkan Menteri Koordinator Bidang Politik Hukum dan Keamanan (Menkopolhukam) Mahfud MD untuk menjelaskan terkait isu dugaan transaksi mencurigakan Rp 349 triliun di Kementerian Keuangan ke DPR RI. Hal ini disampaikan Mahfud MD usai dipanggil oleh Presiden Jokowi di Istana Kepresidenan, Jakarta, Senin (27/3/2023). Mantan Ketua MK itu memastikan bakal menjelaskan ke DPR pada Rabu (29/7/2023). "Presiden meminta saya hadir menjelaskan ke DPR dengan
----------------------------------------

============================================================
TRUE: POLITIK_PEMERINTAHAN → PREDICTED: OLAHRAGA
============================================================

ID    : 60219
TITLE : Satgas Yonif 143/TWEJ Ajak Anak-Anak Pedalaman Papua Bermain Bersama
CONTENT: KEEROM - Satgas Yonif 143/TWEJ kembali hadir di tengah-tengah masyarakat mengajak bermain anak-anak. Kali ini bertempat di Kampung Yuruf, Distrik Yafi, Kab. Keerom, Papua, Minggu (9/4/2023). Dalam keterangannya, Danpos Yuruf Lettu Inf Sukamto menjelaskan bahwa kegiatan tersebut merupakan upaya Satgas Yonif 143/TWEJ untuk memberikan kegiatan anak-anak disaat libur sekolah yang bertujuan menciptajan keceriaan bagi anak-anak, sekaligus berkomunikasi dengan anak-anak di Pedalaman Papua.    Satgas be
----------------------------------------

ID    : 56577
TITLE : Viral Tukang Cuci Piring Bekerja Diantar Mobil Mewah, Ternyata Wanita Kaya Raya
CONTENT: CHENGDU  Penampilan luarnya terihat biasa saja, namun siapa sangka pencuci piring di sebuah restoran di Chengdu, Provinsi Sichuan, China ini ternyata adalah seorang wanita kaya raya. Bahkan dia datang ke tempat kerjanya diantar dengan mobi mewah Bentley. Rekaman dari restoran itu memperlihatkan wanita yang mengekan kaos belang, sepasang sepatu karet dan celemek keluar dari mobil Bentley hitam. Video yang diunggah pada 1 April itu segera menjadi viral di media sosial China dan ramai dibahas warga
----------------------------------------

ID    : 11083
TITLE : Pembahasan Soal dan Kunci Jawaban IPS Kelas 8 Halaman 210 untuk Siswa SMP
CONTENT: IPS kelas 8 halaman 210 dibutuhkan para siswa untuk mencocokkan jawaban mereka dari soal yang sudah dikerjakan. Para guru bisa membimbing muridnya untuk berlatih mengerjakan soal secara mandiri di awal dan mencocokkan jawaban bersama-sama di akhir sesi dengan menggunakan kunci jawaban yang sudah disediakan. Soal dan kunci jawaban IPS kelas 8 halaman 210 untuk ini membahas materi pelajaran yang dikutip dari Belanda melakukan kerja paksa di berbagai daerah. Untuk mengetahui bentuk kerja paksa di d
----------------------------------------

============================================================
TRUE: POLITIK_PEMERINTAHAN → PREDICTED: HUKUM_KRIMINAL
============================================================

ID    : 30508
TITLE : Mengenal Hukum Melaksanakan Salat Tarawih bagi Umat Islam
CONTENT: Hukum melaksanakan bagi umat Islam adalah sunah muakadah, yang berarti sangat dianjurkan untuk dilakukan. Salat tarawih dilakukan oleh umat Islam pada bulan Ramadan setelah salat Isya. Ramadhan merupakan bulan yang sangat dinantikan oleh umat Islam sehingga semua ibadah dalam bulan tersebut sangat sayang untuk dilewatkan. Meski salat tarawih tidak wajib, tapi ibadah yang disyariatkan oleh Rasulullah ini dilaksanakan dengan antusias oleh seluruh umat Islam. Baca juga: Dalam buku yang ditulis oleh
----------------------------------------

ID    : 60164
TITLE : Mantan Waka OJK Rahmat Waluyanto Akan Dimakamkan di San Diego Hills
CONTENT: JAKARTA - Mantan Wakil Ketua (Waka) Otoritas Jasa Keuangan ( OJK ) Rahmat Waluyanto meninggal dunia hari ini, Senin (10/4/2023). Berdasarkan informasi yang diterima, Rahmat meninggal dunia dalam usia 66 tahun di RS Dustira Cimahi pukul 01.22 WIB dini hari.  BACA JUGA: Dia pun rencananya akan disemayamkan di Rumah Duka RSPAD Gatot Subroto, ruang B. Kemudian untuk proses pemakaman akan dilakukan pada esok hari, Selasa (11/4/2023) di San Diego Hills Memorial Park, Krawang. BACA JUGA: Rahmat disebut
----------------------------------------